### ISSUE TITLE
Failed to activate the relative-numbers package

### ISSUE THREAD

**Issue by SurenderLohia** [ridderholt/atom-relative-linenumbers#10]
1. Just Installed
2. And Use: Relative Number -> Toggle
3. Got error 

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.3
**Thrown From**: [relative-numbers](https://github.com/robinridderholt/atom-relative-linenumbers) package, v0.2.0
### Stack Trace

Failed to activate the relative-numbers package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
  at Object.module.exports.activate (/Users/surender/.atom/packages/relative-numbers/lib/relative-numbers.coffee:8:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:792:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -3:40.1.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  6x -3:39.6.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:23.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:23.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -2:22.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -2:19.3.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -2:19.3.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:17.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -2:17 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:12.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 12x -2:04.4.0 blur (atom-text-editor.editor.mini.is-focused)
  2x -1:30.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -1:21.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  7x -1:20.3.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:21 link:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.5.0 relative-numbers:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-sass, v0.1.0
color-picker, v2.0.11
emmet, v2.3.12
highlight-line, v0.11.0
javascript-snippets, v1.0.0
jshint, v1.3.10
linter-csslint, v0.0.14
linter-jshint, v1.1.4
relative-numbers, v0.2.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by ruslanmalogulko** [comment]
have the same issue for me

**Comment by bendman** [comment]
:+1:

**Comment by ghost** [comment]
Hi, thanks for reporting issues! Unfortunately I'm not maintaining this plugin any more and I have unpublished it from Atoms package listing. Perhaps I will have the time in the future to fix the issues which is caused by my plugin not being compatible with Atom 1.0. I will not remove the repository so feel free to fork it.

**Comment by SurenderLohia** [comment]
Cool, Thanks for the replay. It was a cool plugin, thanks for that…

Currently I am using: https://atom.io/packages/relative-line-numbers https://atom.io/packages/relative-line-numbers

Thanks & Regards
Surender Lohia
