### ISSUE TITLE
Cannot read property 'eachEditorView' of undefined.

### ISSUE THREAD

**Issue by Jeffdude** [ridderholt/atom-relative-linenumbers#9]
Steps to reproduce::
1. Create New Window (Shift - Command - N)
2. Open new file (Command - O)

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [relative-numbers](https://github.com/robinridderholt/atom-relative-linenumbers) package, v0.2.0
### Stack Trace

Failed to activate the relative-numbers package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
  at Object.module.exports.activate (/Users/jmilling/.atom/packages/relative-numbers/lib/relative-numbers.coffee:8:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:01.1.0 application:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "naturerainbow-dark-syntax"
    ]
  },
  "relative-numbers": {
    "displayTrueLineNumberOnCurrentLine": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v0.5.1
clipboard-plus, v0.5.1
fonts, v0.5.0
git-diff-details, v0.18.0
linter, v1.2.4
linter-python-pep8, v0.2.0
minimap, v4.12.0
minimap-git-diff, v4.1.7
minimap-linter, v1.0.0
naturerainbow-dark-syntax, v0.1.1
relative-numbers, v0.2.0
run-in-terminal, v0.3.0
vim-mode, v0.55.0
vim-mode-clipboard-plus, v0.1.0

# Dev
No dev packages
```

It's possible this is a fault of my ridiculous amount of packages interfering with yours. I guess I'm just testing if atom truly is 'hackable to the core.' 

If you need anything else, let me know.

**Comment by ghost** [comment]
Hi, thanks for reporting issues! Unfortunately I'm not maintaining this plugin any more and I have unpublished it from Atoms package listing. Perhaps I will have the time in the future to fix the issues which is caused by my plugin not being compatible with Atom 1.0. I will not remove the repository so feel free to fork it.
